Ordinary:
Workcenter:         W1
  RGB:                30;123;173
  Release:            0
  Status:             A

Workcenter:         W2
  RGB:                121;27;133
  Release:            0
  Status:             A

Workcenter:         W3
  RGB:                42;146;39
  Release:            0
  Status:             A

Workcenter:         W4
  RGB:                0;12;170
  Release:            0
  Status:             A

