Shop:               Job
Job:                J1
  RGB:                255;0;0
  Release:            0
  Due:                20
  Weight:             1
  Oper:               Assembly;5;A

Job:                J2
  RGB:                0;255;0
  Release:            1
  Due:                20
  Weight:             1
  Oper:               Packaging;3;A

Job:                J3
  RGB:                0;0;255
  Release:            2
  Due:                20
  Weight:             1
  Oper:               Assembly;4;A

Job:                J4
  RGB:                255;255;0
  Release:            3
  Due:                20
  Weight:             1
  Oper:               Packaging;2;A

Job:                J5
  RGB:                255;128;0
  Release:            5
  Due:                25
  Weight:             1
  Oper:               Assembly;6;A

Job:                J6
  RGB:                128;0;255
  Release:            6
  Due:                26
  Weight:             1
  Oper:               Packaging;5;A

Job:                J7
  RGB:                0;255;255
  Release:            7
  Due:                30
  Weight:             1
  Oper:               Assembly;3;A

