Ordinary:
Workcenter:         Assembly
  RGB:                200;150;100
  Release:            0
  Status:             A
Machine:            A1
    Release:            0
    Status:             A
Machine:            A2
    Release:            0
    Status:             A

Workcenter:         Packaging
  RGB:                100;200;150
  Release:            0
  Status:             A
Machine:            P1
    Release:            0
    Status:             A
Machine:            P2
    Release:            0
    Status:             A

