Ordinary:
Workcenter:         W01
  RGB:                148;110;80
  Release:            0
  Status:             A

Workcenter:         W02
  RGB:                0;0;200
  Release:            0
  Status:             A

Workcenter:         W03
  RGB:                160;0;160
  Release:            0
  Status:             A

Workcenter:         W04
  RGB:                0;192;0
  Release:            0
  Status:             A

